listenaddr: 0.0.0.0
port: 4000
testfiles: [1048576, 10485760, 104857600]
baseinfo:
  bandwidth: false
  display_traffic: true
  display_speedtest: true
  utilities_ping: true
  utilities_traceroute: true
  utilities_iperf3: true
  utilities_iperf3_port_min: 30000
  utilities_iperf3_port_max: 31000
  utilities_speedtestdotnet: true
  utilities_fakeshell: false
app:
  deftimeout: 90
  pingresulttemplate: ""
  pingresultnotlinktemplate: ""
  pingresultnotpingtemplate: ""
  iperffixedport: 0
netset:
  networkadapter:
    onlyshow: []
    dontshow: ["VMware Network Adapter"]
  hideexternalip: false